version: '3'

services:
    server:
        privileged: true
        build: .
        image: karim/ex03/01:tag
        container_name: gitlab-ce-k
        ports:
            - "80:80" 
            - "2222:22"
            - "443:443"
        tty: true
        stdin_open: true

